// WARNING: This file is automatically copied from ../../console/app/frontend/packages/dbu-shared/dbu-shared-constants.ts
// DO NOT EDIT THIS FILE DIRECTLY - all changes must be made in the Rails server directory
// This file is always overwritten everytime 'npm run dev' is run (which executes copy-shared-constants.js)

// This is a shared constants file used across all our TS code, situated in the Rails app front-end "shared" module.
// It is also automatically copied over to the node-server by its pnpm run dev command.

// Nothing to share (everything mostly happens thru ENV variables templated centrally from Ansible).
// So a stub for now.
const DBU_SHARED_CONSTANTS = {};
